version: '3'
services:
  postgres:
    image: 'postgres'
    container_name: 'ks-postgres'
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
    volumes:
      - './.data/pg:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  mongo:
    image: 'mongo'
    container_name: 'ks-mongo'
    environment:
      - MONGO_INITDB_DATABASE=db_name
      - MONGO_INITDB_ROOT_USERNAME=app
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - './.data/mongo:/data/db'
    ports:
      - '27017:27017'